


// function Connect() {
//     var form = document.getElementById('formulario');
//     console.log(form);
//     var datos = new FormData(form);
//     //console.log(datos);
//     console.log(datos.get('Vel'));
//     console.log(datos.get('State'));
//     console.log(datos.get('Dir'));
//     fetch('../update_values.php', {
//         method: 'POST',
//         body: datos
//     })
//         .then(response => response.json())
//         .then(data => {
//             console.log(data);
//         })
// }