document.body.innerHTML += '<nav class="Menu">'+
'<input type="checkbox" id="check">'+
'<label class="Menu__CheckBtn" for="check"><i class="fa-solid fa-bars"></i></label>'+
'<ul class="Menu__Opciones">'+
    '<li><a class="Menu-Link" href="Index.html"><i class="fa-solid fa-house"></i></i>  Inicio </a></li>'+
    '<li><a class="Menu-Link" href="FormText.html"><i class="fa-solid fa-file-lines"></i>  Formato de Texto</a></li>'+
    '<li><a class="Menu-Link" href="FormEtiquetado.html"><i class="fa-solid fa-tag"></i>  Formato de Etiquetado</a></li>'+
    '<li><a class="Menu-Link" href="FormImage.html"><i class="fa-solid fa-file-image"></i>  Formato de imagen</a></li>'+
'</ul>'+
'</nav>';