CREATE TABLE Municipio(
	PK_Id_Mun TINYINT  Auto_Increment NOT NULL,
	Nom_Mun VarChar(250) NOT NULL,
	PRIMARY KEY(PK_Id_Mun)
);

CREATE TABLE Cliente(
	PK_Id_Cli SMALLINT Auto_Increment NOT NULL,
	Nom_C VarChar(180) NOT NULL,
	Ap1_C VarChar(100) NULL,
	Puntos FLOAT NOT NULL,
	PRIMARY KEY(PK_Id_Cli)
);

CREATE TABLE Empleado(
	PK_Id_Emp TINYINT Auto_Increment NOT NULL,
	Nom_E VarChar(180) NOT NULL,
	Ap1_E VarChar(100) NOT NULL,
	Ap2_E VarChar(100) NOT NULL,
	Adm   BIT NOT NULL,
	FN_E DATE NOT NULL,
	CURP_E Char(18) NOT NULL,
	RFC_E VarChar(13) NOT NULL,
	Contra_E VarChar(150) NOT NULL,
	Direc_E VarChar(250) NOT NULL,
	Nom_UE VarChar(180) NOT NULL,
	FK_Id_Mun TINYINT NULL,
	PRIMARY KEY(PK_Id_Emp),
	FOREIGN KEY (FK_Id_Mun) REFERENCES Municipio(PK_Id_Mun)
);

CREATE TABLE Marca(
	PK_Id_Marca INT Auto_Increment NOT NULL,
	Nom_Marc VarChar(200) NOT NULL,
	PRIMARY KEY(PK_Id_Marca)
);

CREATE TABLE Producto(
	PK_Id_Prod SMALLINT Auto_Increment NOT NULL,
	No_Exis SMALLINT NULL,
	Precio FLOAT NOT NULL,
	Descripcion VarChar(250) NOT NULL,
	FK_Id_Marca INT NULL,
	PRIMARY KEY(PK_Id_Prod),
	FOREIGN KEY (FK_Id_Marca) REFERENCES Marca(PK_Id_Marca)
);

CREATE TABLE FacturaD(
	PK_No_FactD SMALLINT  Auto_Increment NOT NULL,
	Cantidad SMALLINT NOT NULL,
	Precio_Un FLOAT NOT NULL,
	Precio_L FLOAT NOT NULL,
	Imp_B FLOAT NOT NULL,
	FK_Id_Prod SMALLINT NULL,
	PRIMARY KEY(PK_No_FactD),
	FOREIGN KEY (FK_Id_Prod) REFERENCES Producto(PK_Id_Prod)
);

CREATE TABLE Proveedor(
	PK_Id_Prov TINYINT Auto_Increment NOT NULL,
	Nom_P VarChar(180) NOT NULL,
	Direc_P VarChar(250) NOT NULL,
	Tel_P VarChar(20) NOT NULL,
	PRIMARY KEY(PK_Id_Prov)
);

CREATE TABLE Factura(
	PK_No_Factura SMALLINT Auto_Increment NOT NULL,
	F_Factura DATE NULL,
	Imp_N FLOAT NOT NULL,
	FK_Id_Emp TINYINT NULL,
	FK_Id_Prov TINYINT NULL,
	FK_No_FactD SMALLINT NULL,
	PRIMARY KEY(PK_No_Factura),
	FOREIGN KEY (FK_Id_Emp) REFERENCES Empleado(PK_Id_Emp),
	FOREIGN KEY (FK_Id_Prov) REFERENCES Proveedor(PK_Id_Prov),
	FOREIGN KEY (FK_No_FactD) REFERENCES FacturaD(PK_No_FactD)
);

CREATE TABLE Ticket(
	PK_No_Ticket SMALLINT Auto_Increment NOT NULL,
	Precio_Lin FLOAT NOT NULL,
	Total_B FLOAT NOT NULL,
	Total_N FLOAT NOT NULL,
	F_Ven DATE NULL,
	FK_Id_Prod SMALLINT NULL,
	FK_Id_Emp TINYINT NULL,
	FK_Id_Cli SMALLINT NULL,
	PRIMARY KEY(PK_No_Ticket),
	FOREIGN KEY (FK_Id_Emp) REFERENCES Empleado(PK_Id_Emp),
	FOREIGN KEY (FK_Id_Prod) REFERENCES Producto(PK_Id_Prod),
	FOREIGN KEY (FK_Id_Cli) REFERENCES Cliente(PK_Id_Cli)
);


/*Trigeger*/
DELIMITER $$
CREATE TRIGGER t_puntos
AFTER INSERT ON ticket FOR EACH ROW 
BEGIN
UPDATE cliente SET puntos = puntos+10 
WHERE pk_id_cli = new.fk_id_cli;
END;
$$
DELIMITER ;


CREATE USER 'DarkKnight12'@'localhost' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON punto_venta1 . * TO 'DarkKinght12'@'localhost';
FLUSH PRIVILEGES;

CREATE USER 'Yoda'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON punto_venta1 . * TO 'Yoda'@'localhost';
FLUSH PRIVILEGES;

INSERT INTO Cliente (PK_Id_Cli, Nom_C, Ap1_C, Puntos) 
VALUES
		(1, 'Emiliano', 'Gonzalez', 20),
		(2, 'Issac', 'Robles', 0);	

INSERT Municipio (Nom_Mun)
VALUES
	('Acatic'), 
	('Acatlan de Juarez'), 
	('Ahualulco de Mercado'), 
	('Amacueca'), 
	('Amatitan'), 
	('Ameca'), 
	('Arandas'), 
	('Atemajac de Brizuela'), 
	('Atengo'), 
	('Atenguillo '), 
	('Atotonilco el Alto'), 
	('Atoyac'), 
	('Autlan de Navarro'), 
	('Ayotlan'), 
	('Ayutla'), 
	('Bolanos'), 
	('Cabo Corrientes'), 
	('Canadas de Obregon '), 
	('Casimiro Castillo'), 
	('Chapala'), 
	('Chimaltitan '), 
	('Chiquilistlan'), 
	('Cihuatlan'), 
	('Cocula'), 
	('Colotlan'), 
	('Concepcion de Buenos Aires'), 
	('Cuautitlan de Garcia Barragan'), 
	('Cuautla '), 
	('Cuquio'), 
	('Degollado'), 
	('Ejutla '), 
	('El Arenal'), 
	('El Grullo'), 
	('El Limon'), 
	('El Salto'), 
	('Encarnacion de Diaz'), 
	('Etzatlan'), 
	('Gomez Farias'), 
	('Guachinango '), 
	('Guadalajara'), 
	('Hostotipaquillo'), 
	('Huejucar'), 
	('Huejuquilla el Alto'), 
	('Ixtlahuacan de los Membrillos'), 
	('Ixtlahuacan del Rio'), 
	('Jalostotitlan'), 
	('Jamay'), 
	('Jesus Maria'), 
	('Jilotlan de los Dolores'), 
	('Jocotepec'), 
	('Juanacatlan'), 
	('Juchitlan'), 
	('La Barca'), 
	('La Huerta'), 
	('La Manzanilla de la Paz '), 
	('Lagos de Moreno'), 
	('Magdalena'), 
	('Mascota'), 
	('Mazamitla'), 
	('Mexticacan'), 
	('Mezquitic '), 
	('Mixtlan '), 
	('Ocotlan'), 
	('Ojuelos de Jalisco'), 
	('Pihuamo'), 
	('Poncitlan'), 
	('Puerto Vallarta'), 
	('Quitupan'), 
	('San Cristobal de la Barranca '), 
	('San Diego de Alejandria'), 
	('San Gabriel'), 
	('San Ignacio Cerro Gordo'), 
	('San Juan de los Lagos'), 
	('San Juanito de Escobedo'), 
	('San Julian'), 
	('San Marcos '), 
	('San Martin de Bolanos '), 
	('San Martin Hidalgo'), 
	('San Miguel el Alto'), 
	('San Pedro Tlaquepaque'), 
	('San Sebastian del Oeste'), 
	('Santa Maria de los angeles '), 
	('Santa Maria del Oro '), 
	('Sayula'), 
	('Tala'), 
	('Talpa de Allende'), 
	('Tamazula de Gordiano'), 
	('Tapalpa'), 
	('Tecalitlan'), 
	('Techaluta de Montenegro '), 
	('Tecolotlan'), 
	('Tenamaxtlan'), 
	('Teocaltiche'), 
	('Teocuitatlan de Corona'), 
	('Tepatitlan de Morelos'), 
	('Tequila'), 
	('Teuchitlan'), 
	('Tizapan el Alto'), 
	('Tlajomulco de Zuniga'), 
	('Toliman'), 
	('Tomatlan'), 
	('Tonala'), 
	('Tonaya'), 
	('Tonila'), 
	('Totatiche'), 
	('Tototlan'), 
	('Tuxcacuesco '), 
	('Tuxcueca'), 
	('Tuxpan'), 
	('Union de San Antonio'), 
	('Union de Tula'), 
	('Valle de Guadalupe'), 
	('Valle de Juarez'), 
	('Villa Corona'), 
	('Villa Guerrero'), 
	('Villa Hidalgo'), 
	('Villa Purificacion'), 
	('Yahualica de Gonzalez Gallo'), 
	('Zacoalco de Torres'), 
	('Zapopan'), 
	('Zapotiltic'), 
	('Zapotitlan de Vadillo');
	
INSERT Empleado (PK_Id_Emp, Nom_E, Ap1_E, Ap2_E, Adm, FN_E, 
        CURP_E, RFC_E, Contra_E, Direc_E, Nom_UE, FK_Id_Mun) 
VALUES (1, 'CARLOS DANIEL', 'Lozano', 'Vazquez', 1, '2003-01-17' , 'LOVC030117HJCZZRA3', 'LOVC030117A65',
        '0906Gean.0906', 'Calle Laurel 10, Col. Higuera', 'DarkKnight', 120),
		(2, 'Emilio', 'Camarena', 'Nava', 0, '2003-05-17', 'CANE030517HJCMVMB2', 'CANE030517B27',
		'CaNava012', 'Calle Vergeles 12, Col Tabachines', 'CaNavaEmi', 120);

INSERT INTO Marca (Nom_Marc) VALUES
('Paper Mate'),
('Bic'),
('Vinci'),
('Pelikan'),
('Escolar'),
('Baco'),
('Scribe'),
('Estrella'),
('Barrilito'),
('Crayola'),
('Top'),
('MAE'),
('CASIO'),
('Azor'),
('Signal'),
('Berol'),
('Fiero'),
('Tuk'),
('Prismacolor'),
('Leoncito'),
('Mapita'),
('Magistral '),
('Libre');

INSERT INTO Producto (PK_Id_Prod, No_Exis, Precio, Descripcion, FK_Id_Marca) VALUES
(1, 29, 4.5, 'lapiz No. 2', 12),
(2, 34, 5, 'Lapiz No.2 Mirado Hexagonal', 1),
(3, 43, 5, 'Lapiz No.2 Triangular', 4),
(4, 48, 5, 'Pluma de cristal Color Negra', 2),
(5, 34, 5, 'Pluma de cristal Color Azul', 2),
(6, 30, 5, 'Pluma de Cristal Color Verde', 2),
(7, 28, 5, 'Pluma de cristal color Roja', 2),
(8, 18, 5, 'Pluma Kilometrica Azul', 1),
(9, 8, 5, 'Pluma Kilometrica Negra', 1),
(10, 43, 5, 'Pluma Kilometrica Verde', 1),
(11, 58, 5, 'Pluma Kilometrica Roja', 1),
(12, 44, 5, 'Pluma Kilometrica Punta Fina Roja', 1),
(13, 44, 5, 'Pluma Kilometrica Punta Fina Azul', 1),
(14, 18, 5, 'Pluma Kilometrica Punta Fina Negra', 1),
(15, 26, 5, 'Pluma Kilometrica verde pastel', 1),
(16, 44, 5, 'Pluma Kilometrica azul pastel', 1),
(17, 14, 5, 'Pluma Kilometrica rosa pastel', 1),
(18, 21, 5, 'Pluma Kilometrica Morada ', 1),
(19, 28, 5, 'Pluma Kilometrica naranja ', 1),
(20, 47, 5, 'Bicolor tamaÃ±o de lapiz No.2', 4),
(21, 36, 11, 'Bicolor Grande', 4),
(22, 4, 1.5, 'Zacapuntas plastico', 12),
(23, 21, 7, 'Zacapuntas metal', 12),
(24, 4, 10, 'Zacapuntas metal 2ble entrada', 12),
(25, 35, 18, 'Corrector de estilo pluma ', 2),
(26, 31, 13, 'Corrector de estilo brocha', 2),
(27, 31, 3, 'Borrador Blanco', 4),
(28, 10, 3, 'Borrador Migajon pequeÃ±o', 12),
(29, 59, 6, 'Borrador Migajon Grande', 12),
(30, 44, 12, 'Pintura de agua Roja', 3),
(31, 15, 12, 'Pintura de agua Morada', 3),
(32, 31, 12, 'Pintura de agua  Verde', 3),
(33, 37, 12, 'Pintura  de agua Gris', 3),
(34, 25, 12, 'Pintura  de agua CafÃ©', 3),
(35, 20, 12, 'Pintura de agua Celeste', 3),
(36, 18, 12, 'Pintura  de agua Amarilla', 3),
(37, 40, 12, 'Pintura  de agua Naranja', 3),
(38, 46, 12, 'Pintura  de agua Durazno', 3),
(39, 48, 12, 'Pintura  de agua Negra', 3),
(40, 50, 12, 'Pintura de agua Blanca', 3),
(41, 57, 12, 'Pintura  de agua Azul Marino', 3),
(42, 15, 12, 'Pintura  de agua Verde Limon', 3),
(43, 39, 30, 'Colores de 12 pz. ', 20),
(44, 55, 70, 'Colores de 12 pz. Fantasy', 1),
(45, 28, 157, 'Colores de 24 pz.', 19),
(46, 32, 94, 'Colores de 24 pz.', 10),
(47, 27, 20, 'Colores de 12 pz.', 21),
(48, 11, 15, 'Marcatextos Naranja', 14),
(49, 14, 15, 'Marcatextos Azul', 14),
(50, 46, 15, 'Marcatextos Verde', 14),
(51, 31, 15, 'Marcatextos Amarillo', 14),
(52, 33, 15, 'Marcatextos Rosa', 14),
(53, 11, 15, 'Marcatextos Rojo', 14),
(54, 38, 12, 'Marcador de Agua Azul', 4),
(55, 5, 12, 'Marcador de Agua Verde', 4),
(56, 57, 12, 'Marcador de Agua Rosa', 4),
(57, 55, 12, 'Marcador de Agua Morado', 4),
(58, 29, 12, 'Marcador de Agua Gris', 4),
(59, 11, 12, 'Marcador de Agua Rojo', 4),
(60, 58, 12, 'Marcador de Agua Negro', 4),
(61, 18, 12, 'Marcador de Agua CafÃ©', 4),
(62, 47, 12, 'Marcador de Agua Amarillo', 4),
(63, 53, 12, 'Marcador de Agua Naranja', 4),
(64, 38, 26, 'Marcador de aceite 2ble punta Azul', 15),
(65, 13, 26, 'Marcador de aceite 2ble punta Negro', 15),
(67, 47, 18, 'Marcador de Aceite Azul', 16),
(68, 37, 17, 'Marcador para pintarron Negro', 22),
(69, 32, 17, 'Marcador para pintarron Azul', 22),
(70, 60, 17, 'Marcador para pintarron Verde', 22),
(71, 60, 17, 'Marcador para pintarron Rojo', 22),
(72, 54, 15, 'Marcador de cera rojo', 4),
(73, 18, 15, 'Marcador de cera Azul', 4),
(74, 51, 15, 'Marcador de cera Verde', 4),
(75, 30, 10, 'Plastilina Verde', 5),
(76, 34, 10, 'Plastilina roja', 5),
(77, 32, 10, 'Plastilina Azul', 5),
(78, 56, 10, 'Plastilina CafÃ©', 5),
(79, 25, 10, 'Plastilina Gris', 5),
(80, 26, 10, 'Plastilina Rosa', 5),
(81, 18, 10, 'Plastilina Blanca', 5),
(82, 41, 10, 'Plastilina Negra', 5),
(83, 39, 10, 'Plastilina Verde Limon', 5),
(84, 54, 10, 'Plastilina celeste', 5),
(85, 30, 10, 'Plastilina Naranja', 5),
(86, 20, 10, 'Plastilina amarilla', 5),
(87, 46, 10, 'Plastilina Morada', 5),
(88, 87, 5, 'Cartulina Azul pastel', 23),
(89, 100, 5, 'Cartulina Rosa pastel', 23),
(90, 21, 5, 'Cartulina Verde Pastel', 23),
(91, 95, 4, 'Cartulina blanca', 23),
(92, 16, 7, 'Cartulina Azul Marino', 23),
(93, 62, 7, 'Cartulina Roja', 23),
(94, 36, 7, 'Cartulina Morada', 23),
(95, 58, 7, 'Cartulina Negra', 23),
(96, 65, 7, 'Cartulina Naranja', 23),
(97, 83, 7, 'Cartulina Verde Bandera', 23),
(98, 94, 32, 'juego de geometria', 6),
(99, 68, 160, 'Calculadora cientifica', 13),
(100, 4, 40, 'Abaco', 6),
(101, 11, 20, 'Cuaderno profesional Raya', 7),
(102, 88, 20, 'Cuaderno profesional 2ble Raya', 7),
(103, 64, 20, 'Cuaderno profesional Cuadro Chico', 7),
(104, 52, 20, 'Cuaderno profesional Cuadro Grande', 7),
(105, 58, 20, 'Cuaderno profesional dibujo', 7),
(106, 57, 20, 'Cuaderno profesional Mixto', 7),
(107, 93, 15, 'Cuaderno forma francesa espiral Raya', 7),
(108, 84, 15, 'Cuaderno forma francesa espiral 2ble raya', 7),
(109, 23, 15, 'Cuaderno forma francesa espiral Cuadro Grande', 7),
(110, 79, 15, 'Cuaderno forma francesa espiral Cuadro chico', 7),
(111, 7, 15, 'Cuaderno forma francesa espiral Dibujo', 7),
(112, 62, 15, 'Cuaderno forma Italiana espiral Raya', 8),
(113, 58, 15, 'Cuaderno forma Italiana espiral 2ble raya', 8),
(114, 28, 15, 'Cuaderno forma Italiana espiral Cuadro Grande', 8),
(115, 44, 15, 'Cuaderno forma Italiana espiral Cuadro chico', 8),
(116, 92, 15, 'Cuaderno forma Italiana espiral Dibujo', 8),
(117, 8, 180, 'Recopilador', 7),
(118, 68, 32, '100 Hojas para recopilador Raya', 7),
(119, 35, 32, '100 Hojas para recopilador 2ble Raya', 7),
(120, 42, 32, '100 Hojas para recopilador Cuadro chico', 7),
(121, 95, 32, '100 Hojas para recopilador Cuadro grande', 7),
(122, 47, 9, 'Tijeras', 9),
(123, 52, 10, 'Regla madera', 9),
(124, 54, 15, 'Regla metalica', 9),
(125, 30, 6, 'Regla plastico', 9),
(126, 82, 17, 'Regla flexible', 12),
(127, 34, 6, 'Transportador', 9),
(128, 73, 45, 'calculadora basica', 9),
(129, 59, 60, 'Pistola de silicon', 9),
(130, 10, 2, 'Barra de silicon', 23),
(131, 60, 5, 'Cinta diurex', 18),
(132, 90, 20, 'Cinta masking tape', 18),
(133, 96, 30, 'Cinta canela', 18),
(134, 41, 28, 'Cinta diurex grande', 18),
(135, 35, 9, 'Resistol de barra 7gr', 11),
(136, 62, 16, 'Resitol de barra 16gr', 11),
(137, 61, 19, 'Resitol de barra 20gr', 11),
(138, 99, 24, 'Resistol de barra 27 gr', 11),
(139, 2, 20, 'Rafia verde', 17),
(140, 12, 20, 'Rafia CafÃ©', 17),
(141, 35, 20, 'Rafia blanca', 17),
(142, 17, 20, 'Rafia amarilla', 17),
(143, 30, 32, 'Crayolas 12 pz', 10),
(144, 20, 23, 'Crayolas pequenias 12 pz', 10),
(145, 37, 10, 'Crayolas pequenias 8 pz', 23),
(146, 55, 60, 'Bote con crayolas 24 pzas', 4);

INSERT INTO Proveedor (PK_Id_Prov, Nom_P, Direc_P, Tel_P) VALUES
(1, 'Sajor', 'Calle Rio Juarez No. 1447, Col. El Rosario. C.P. 44898, Guadalajara, Jalisco México.', '33 3942 7070');

